### ISSUE TITLE
Markdown practice

### ISSUE THREAD

**Issue by pzhaonet** [pzhaonet/dph206-2020#3]
This issue is for markdown exercise.

**Comment by Bella-yijing** [comment]
#  Practice

1. *There is a formula:*

- $E = mc^2$  from [link](https://pzhaonet.github.io/dph206-2020/#basic-information)

2. **There is a picture:**

-  
![image](https://user-images.githubusercontent.com/61084379/75229419-d2dfc480-57ec-11ea-93f3-d1afe0d431bc.png)

>   The cocncerntation of PM~2.5~ is130.7μg/m^3^

**Comment by Wanqi-Wang** [comment]
When you are reading a epidemiology report or news, you may often see people use **sensitivity** or **specificity**, what are them? What's the difference?
Now, let me introduce it for you:)


- <li>Sensitivity</li>
- <li>Specificity</li>
- <li>Practice test</li>

![](C:\Users\Wanqi\Pictures\Saved Pictures\sen.png)

**Comment by Wanqi-Wang** [comment]
When you are reading a epidemiology report or news, you may often see people use **sensitivity** or **specificity**, what are them? What's the difference?
Now, let me introduce it for you:)


- Sensitivity
- Specificity
- Practice test

 `[](C:\Users\Wanqi\Pictures\Saved` Pictures\sen.png)

**Comment by Wanqi-Wang** [comment]
- [x] week 1 
- [ ] week 2
- [ ] week 3

**Comment by Wanqi-Wang** [comment]
# Who is AM?
*Awesome me*
**Awesome me**

Awesome used to say that:
>Awesome me is awesome

Awesome~me
$H~2~O$ is a liquid

1.awesome
2.me




![31](https://user-images.githubusercontent.com/61083855/75252008-bf495380-5816-11ea-9744-3fac0baf0b0f.PNG)

AM has a dog, a yellow cute dog, when AM get this dog, she was major in chemistry, and give the dog a name: C<sub>6</sub>H<sub>12</sub>O<sub>6</sub></p>, AM call it glucose, while sometimes call it sugar, which makes it less weird.

AM like epidemiology, actually, very much! AM can tell you:
>Epidemiology is the *study* and *analysis* of the distribution (who, when, and where), patterns and determinants of health and disease conditions in defined populations.

AM like computer science, as well, also, AM has moral evaluation on coding and analysis software, for example, AM has used several software in research, but refuse Python, even it's free. On the other hand, AM use had oop, why? because:

![31](https://cn.bing.com/images/search?view=detailV2&id=579925330C735224739662BC61492973766A897C&thid=OIP.rnShCJV7pAMEeRk0g2kOzQHaE7&mediaurl=http%3A%2F%2Fimages.techhive.com%2Fimages%2Farticle%2F2014%2F09%2Fhadoop-elephant-100453407-primary.idge.png&exph=413&expw=620&q=hadoop+elephant+logo&selectedindex=0&ajaxhist=0&vt=0&eim=1,2,6)
![31](https://cn.bing.com/images/search?view=detailV2&id=6448F726492EF15411C57C0263C31BC501A4F940&thid=OIP.vuTA1iG5R87PZY70DJ48MQHaE-&mediaurl=https%3A%2F%2Fcdn.journaldev.com%2Fwp-content%2Fuploads%2F2015%2F08%2Fhadoop-logo.jpg&exph=196&expw=292&q=hadoop+elephant+logo&selectedindex=6&ajaxhist=0&vt=0&eim=1,2,6&ccid=vuTA1iG5&simid=608033709229606715&pivotparams=insightsToken%3Dccid_rnShCJV7*mid_579925330C735224739662BC61492973766A897C*simid_608048827531527216*thid_OIP.rnShCJV7pAMEeRk0g2kOzQHaE7&iss=VSI)

Even AM like math in college, AM don't like high school math, which you need to memory lots of formula. for example, a<sup>2</sup>+b<sup>2</sup>=c<sup>2</sup>, when it is a right triangle, so what is "wrong" triangle, change "=" to "<" or ">". There are lots of formula, I don't think it was useful as well, now, i don't need to learn it, but my sister have to learn it. 💢 

Learn more? Click this link, you will be deeply surprise, [link](https://c8.alamy.com/comp/HPJK7N/physical-vector-seamless-pattern-with-formulas-equations-and-figures-HPJK7N.jpg)

**Comment by pzhaonet** [comment]
Have fun. 👩‍🚀
